import { useAddress, useMetamask } from "@thirdweb-dev/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const connectWithMetamask = useMetamask();
  const address = useAddress();
  const router = useRouter();

  useEffect(() => {
    if (address) router.replace("/listings");
  }, [address]);

  return (
    <div className="home">
      <Head>
        <title>NFT Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button className="home__button" onClick={connectWithMetamask}>
        Connect using Metamask
      </button>
    </div>
  );
}
